//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Client.Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.StockWebServiceSoap")]
    public interface StockWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name codes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        Stock.Client.Web.ServiceReference1.GetStockPriceResponse GetStockPrice(Stock.Client.Web.ServiceReference1.GetStockPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceResponse> GetStockPriceAsync(Stock.Client.Web.ServiceReference1.GetStockPriceRequest request);
        
        // CODEGEN: Generating message contract since element name codes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPriceSigned", ReplyAction="*")]
        Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse GetStockPriceSigned(Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPriceSigned", ReplyAction="*")]
        System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse> GetStockPriceSignedAsync(Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPrice", Namespace="http://tempuri.org/", Order=0)]
        public Stock.Client.Web.ServiceReference1.GetStockPriceRequestBody Body;
        
        public GetStockPriceRequest() {
        }
        
        public GetStockPriceRequest(Stock.Client.Web.ServiceReference1.GetStockPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codes;
        
        public GetStockPriceRequestBody() {
        }
        
        public GetStockPriceRequestBody(string codes) {
            this.codes = codes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Stock.Client.Web.ServiceReference1.GetStockPriceResponseBody Body;
        
        public GetStockPriceResponse() {
        }
        
        public GetStockPriceResponse(Stock.Client.Web.ServiceReference1.GetStockPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStockPriceResult;
        
        public GetStockPriceResponseBody() {
        }
        
        public GetStockPriceResponseBody(string GetStockPriceResult) {
            this.GetStockPriceResult = GetStockPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceSignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPriceSigned", Namespace="http://tempuri.org/", Order=0)]
        public Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequestBody Body;
        
        public GetStockPriceSignedRequest() {
        }
        
        public GetStockPriceSignedRequest(Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceSignedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codes;
        
        public GetStockPriceSignedRequestBody() {
        }
        
        public GetStockPriceSignedRequestBody(string codes) {
            this.codes = codes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceSignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPriceSignedResponse", Namespace="http://tempuri.org/", Order=0)]
        public Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponseBody Body;
        
        public GetStockPriceSignedResponse() {
        }
        
        public GetStockPriceSignedResponse(Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceSignedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStockPriceSignedResult;
        
        public GetStockPriceSignedResponseBody() {
        }
        
        public GetStockPriceSignedResponseBody(string GetStockPriceSignedResult) {
            this.GetStockPriceSignedResult = GetStockPriceSignedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockWebServiceSoapChannel : Stock.Client.Web.ServiceReference1.StockWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockWebServiceSoapClient : System.ServiceModel.ClientBase<Stock.Client.Web.ServiceReference1.StockWebServiceSoap>, Stock.Client.Web.ServiceReference1.StockWebServiceSoap {
        
        public StockWebServiceSoapClient() {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Stock.Client.Web.ServiceReference1.GetStockPriceResponse Stock.Client.Web.ServiceReference1.StockWebServiceSoap.GetStockPrice(Stock.Client.Web.ServiceReference1.GetStockPriceRequest request) {
            return base.Channel.GetStockPrice(request);
        }
        
        public string GetStockPrice(string codes) {
            Stock.Client.Web.ServiceReference1.GetStockPriceRequest inValue = new Stock.Client.Web.ServiceReference1.GetStockPriceRequest();
            inValue.Body = new Stock.Client.Web.ServiceReference1.GetStockPriceRequestBody();
            inValue.Body.codes = codes;
            Stock.Client.Web.ServiceReference1.GetStockPriceResponse retVal = ((Stock.Client.Web.ServiceReference1.StockWebServiceSoap)(this)).GetStockPrice(inValue);
            return retVal.Body.GetStockPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceResponse> Stock.Client.Web.ServiceReference1.StockWebServiceSoap.GetStockPriceAsync(Stock.Client.Web.ServiceReference1.GetStockPriceRequest request) {
            return base.Channel.GetStockPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceResponse> GetStockPriceAsync(string codes) {
            Stock.Client.Web.ServiceReference1.GetStockPriceRequest inValue = new Stock.Client.Web.ServiceReference1.GetStockPriceRequest();
            inValue.Body = new Stock.Client.Web.ServiceReference1.GetStockPriceRequestBody();
            inValue.Body.codes = codes;
            return ((Stock.Client.Web.ServiceReference1.StockWebServiceSoap)(this)).GetStockPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse Stock.Client.Web.ServiceReference1.StockWebServiceSoap.GetStockPriceSigned(Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest request) {
            return base.Channel.GetStockPriceSigned(request);
        }
        
        public string GetStockPriceSigned(string codes) {
            Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest inValue = new Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest();
            inValue.Body = new Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequestBody();
            inValue.Body.codes = codes;
            Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse retVal = ((Stock.Client.Web.ServiceReference1.StockWebServiceSoap)(this)).GetStockPriceSigned(inValue);
            return retVal.Body.GetStockPriceSignedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse> Stock.Client.Web.ServiceReference1.StockWebServiceSoap.GetStockPriceSignedAsync(Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest request) {
            return base.Channel.GetStockPriceSignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Stock.Client.Web.ServiceReference1.GetStockPriceSignedResponse> GetStockPriceSignedAsync(string codes) {
            Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest inValue = new Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequest();
            inValue.Body = new Stock.Client.Web.ServiceReference1.GetStockPriceSignedRequestBody();
            inValue.Body.codes = codes;
            return ((Stock.Client.Web.ServiceReference1.StockWebServiceSoap)(this)).GetStockPriceSignedAsync(inValue);
        }
    }
}
