//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Client.Console.StockServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceReference.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetAll", ReplyAction="http://tempuri.org/IStockService/GetAllResponse")]
        string GetAll(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetAll", ReplyAction="http://tempuri.org/IStockService/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/Get", ReplyAction="http://tempuri.org/IStockService/GetResponse")]
        string Get(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/Get", ReplyAction="http://tempuri.org/IStockService/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : Stock.Client.Console.StockServiceReference.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<Stock.Client.Console.StockServiceReference.IStockService>, Stock.Client.Console.StockServiceReference.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll(int value) {
            return base.Channel.GetAll(value);
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync(int value) {
            return base.Channel.GetAllAsync(value);
        }
        
        public string Get(int value) {
            return base.Channel.Get(value);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(int value) {
            return base.Channel.GetAsync(value);
        }
    }
}
